# Generated by Django 5.0.6 on 2024-07-04 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trainee',
            new_name='Practitioner',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_trainee',
            new_name='is_practitioner',
        ),
    ]
